// Generated by https://quicktype.io

export interface Nbatest {
    resource:   string;
    parameters: Parameters;
    resultSets: ResultSet[];
}

export interface Parameters {
    TeamID: number;
}

export interface ResultSet {
    name:    string;
    headers: string[];
}
